Enhancements
instana/synthetic-synctl pull request #39
Opened 2023-11-16 07:16 UTC by swethalohith2

## What
some enhancements 

## References
[Kanban card](https://instana.kanbanize.com/ctrl_board/132/cards/145985/details/)

2023-11-16 09:09 UTC, rongzhus commented on synctl
> +            '--severity', type=str, metavar="<string>", help="severity of alert")
```suggestion
            '--severity', type=str, metavar="<string>", choices=["warning", "critical"], help="severity of alert")
```

2023-11-16 09:10 UTC, rongzhus commented on synctl
> +            '--severity', type=str, metavar="<string>", help="severity of alert")
```suggestion
            '--severity', type=str, metavar="<string>", choices=["warning", "critical"], help="severity of alert")
```

2023-11-16 11:44 UTC, rongzhus requested changes
got an error when update `--violation-count 4`
```
synctl update alert 74PZ6WlZQn-qG0YjsEcFOQ --violation-count 4
Traceback (most recent call last):
  File "/Users/shangrz/Desktop/instana-integration/instana-public/synthetic-synctl/./synctl", line 4274, in <module>
    main()
  File "/Users/shangrz/Desktop/instana-integration/instana-public/synthetic-synctl/./synctl", line 4235, in main
    update_alert.update_violation_count(get_args.violation_count)
  File "/Users/shangrz/Desktop/instana-integration/instana-public/synthetic-synctl/./synctl", line 2694, in update_violation_count
    self.smart_alert_config["timeThreshold"]["violationsCount"] = violation_count
AttributeError: 'UpdateSmartAlert' object has no attribute 'smart_alert_config'
```

2023-11-17 05:00 UTC, rongzhus approved these changes

2023-11-17 05:07 UTC, rui1234 commented on README.md
> +--severity <string>                   the severity of alert is either Warning or Critical
the description says Warning/Critical, but the example is warning/critical

2023-11-17 09:43 UTC, merged